name: update-resume

on:
  push:
    branches:
      - resume

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Use Node.js 19.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Archive Latest Resume Website
        uses: actions/upload-artifact@v4
        with:
          name: personal-website-artifact
          path: |
            build

  deploy-github-page:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: personal-website-artifact
          path: atomyyyy.github.io
      - name: Push Change
        run: |
          git add --all
          git commit -m "chore: update personal page"
          git push origin gh-pages
