name: update-calendar

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Preparation Branch
        uses: actions/checkout@v4
        with:
          ref: calendar-ics
      - name: Set Current Date
        run: echo "CURRENT_DATETIME=$(date -u +'%Y%m%d-%H%m')" >> $GITHUB_ENV"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Dependency
        run: npm install
      - name: Prepare Calendar
        run: npm run start
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      - name: Archive Latest Calendar
        uses: actions/upload-artifact@v4
        with:
          name: vtuber-calendar
          path: |
            calendar
      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
      - name: Push Backup File
        run: |
          git add data
          git commit -m "chore: [$CURRENT_DATETIME] backup historical schedule"
          git push origin calendar-ics
  push:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Default Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Clean Up Calendar Folder
        run: rm calendar/*
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: vtuber-calendar
          path: calendar
      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
      - name: Push Change
        run: |
          git add calendar/vtuber.ics
          git commit -m "chore: [$CURRENT_DATETIME] refresh calendar"
          git push origin gh-pages
