name: update-calendar

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Preparation Branch
      - uses: actions/checkout@v4
        with:
          ref: calendar-ics
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Dependency
        run: npm install
      - name: Prepare Calendar
        run: npm run start
      - name: Archive Latest Calendar
        uses: actions/upload-artifact@v4
        with:
          name: vtuber-calendar
          path: |
            calendar
  release:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Default Branch
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Clean Up Calendar Folder
      - run: rm calendar/*
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: vtuber-calendar
      - name: Commit and push change
        run: |
          git add calendar/vtuber.ics
          git commit -m "chore: refresh calendar"
          git push origin gh-pages
